### ISSUE TITLE
求管理员账号密码

### ISSUE THREAD

**Issue by purebluesong** [HIT-Alibaba/Commission#1]
不然这个系统进不去啊
PS：老师让做什么啊，没大看懂……

**Comment by skyline75489** [comment]
@jasonlvhit  你还记得吗？。。。

**Comment by jasonlvhit** [comment]
这个吗？
![image](https://cloud.githubusercontent.com/assets/5202391/14271659/b3adc726-fb2d-11e5-83b6-e4bceea54502.png)

**Comment by purebluesong** [comment]
get！thanks

**Comment by purebluesong** [comment]
get！thanks
